[build]
  functions = "functions"

# rinkeby: port 3001
# mainnet: no port

# proxy server media
[[redirects]]
  from = "/gif/*"
  to = "http://164.92.233.6/gif/:splat"
  status = 200

# proxy server media
[[redirects]]
  from = "/get/*"
  to = "http://164.92.233.6/get/:splat"
  status = 200

# proxy server media
[[redirects]]
  from = "/stylesheets/*"
  to = "http://164.92.233.6/stylesheets/:splat"
  status = 200



# mainnent server proxy (no port)
  [[redirects]]
    from = "/api/1/*"
    to = "http://164.92.233.6/:splat"
    status = 200

# rinkeby server proxy
[[redirects]]
  from = "/api/4/*"
  to = "http://164.92.233.6:3001/:splat"
  status = 200

# rinkeby tokenURI proxy
[[redirects]]
  from = "/v1/metadata/*"
  to = "http://164.92.233.6/v1/metadata/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200